### PR TITLE
Add Parallel Computing Command Example

### PR DESCRIPTION
**Pull request by jianch**
Hi Dan,

Maybe it's worthwhile to add parallel computing example to take advantage of modern computers' multicore computing ability. 

Jian

### CODE REVIEW

**Comment by palday** [comment]
I would prefer to have this as a completely separate example (i.e. in a different file) than the main example. Not everybody has the parallel computing toolbox and there are some things that won't place nice with a parallel for loop (especially as we have not-yet-public experiments with the multicore version of LIBLINEAR and stacking parallelism like that is usually counterproductive). 

So move the parallel example to another file (e.g. ` EXAMPLE_run_decoding_analyses_with_parallel_toolbox.m`) and include a few notes in the comments about common configuration issues (e.g. setting the maximum number of cores to use; perhaps something to the effect about why using half your (logical) cores is sometimes faster than using all of them due to HyperThreading, etc.). 

We (or you!) can then use this to expand the Wiki with an extra section on parallelism.

**Comment by Feugs** [comment]
Hi Jian,

Thanks for your suggestion and code contribution! I agree with Phillip that for now we should have parallel computing capability implemented in a separate `EXAMPLE_run_decoding_analyses_with_parallel_toolbox` config file, rather than the main config file. This will allow existing users that do not have the parallel computing toolbox to keep using DDTBOX.

Also, here are a few notes on contributing to DDTBOX. I will update the [Guide to Contributing](https://github.com/DDTBOX/DDTBOX/wiki/Contributing-to-DDTBOX) with this extra information later today (so thanks for bringing these issues to my attention). 

1) When you plan to add a new feature it is a good idea to mention this in advance by creating a new issue in the [Issue Tracker](https://github.com/DDTBOX/DDTBOX/issues). This allows us to discuss in advance with you the planned feature, and how it might be best integrated into the toolbox. It would be great to include any comments or notes on the best settings for parfor loops (e.g. number of cores) in the issue description or comments, so that we (in collaboration with you) can work these notes into the documentation/wiki.

2) For DDTBOX we use a [Gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) to manage our project and our Git repository. We have 3 main branch types in our project: master, dev and feature branches. The master branch is only updated when we create a new release of the toolbox, and all of the ongoing development happens on the dev branch. When adding a new feature it is best to make a feature branch off of dev, and then make a pull request to merge your feature branch into the dev branch. See the Gitflow workflow guide linked above for a tutorial on how to do this.

Kind regards,

Daniel

**Comment by jianch** [comment]
Hi Philip and Dan,

I totally agree with your opinion, it's my first time to do a pull request, so I think the way you described is a better one. So let's start from creating a new issue.

Jian

**Comment by Feugs** [comment]
Hi Jian,

No worries, and I'm looking forward to discussing how we can make the toolbox much faster using parallel computing. By the way, I just updated the [Guide to Contributing](https://github.com/DDTBOX/DDTBOX/wiki/Contributing-to-DDTBOX) to include step-by-step instructions on how to contribute new code. Thanks so much for your work so far, and for contributing to open source software!

**Pull request closed without merging**
